version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: teacherdung-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teacherdung
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./teacherdung-backend
      dockerfile: Dockerfile
    container_name: teacherdung-nestjs-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/teacherdung?schema=public
      # Add Cloudflare R2 configurations here if needed
      CLOUDFLARE_R2_ACCESS_KEY_ID: ""
      CLOUDFLARE_R2_SECRET_ACCESS_KEY: ""
      CLOUDFLARE_R2_BUCKET_NAME: ""
      CLOUDFLARE_R2_ENDPOINT: ""
      CLOUDFLARE_R2_PUBLIC_URL: ""
    ports:
      - '3001:3001'
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teacherdung-nextjs-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://163.61.72.199:3001
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
